fix(README): DatabaseName is required
When configuring the database via MXRUNTIME_ environment variables,
MXRUNTIME_DatabaseName seems to be required.

Not providing this results in:
> ERROR - M2EE: An error occurred while initializing the Runtime: Database name is not set.
> ERROR - M2EE: com.mendix.m2ee.api.AdminException: An error occurred while initializing the Runtime: Database name is not set.
>     at com.mendix.basis.impl.MxRuntimeImpl.start(MxRuntimeImpl.java:368)
> Caused by: com.mendix.connectionbus.ConnectionBusRuntimeException: Database name is not set.
> ERROR: Executing start did not succeed: result: 1, message: An error occurred while initializing the Runtime: Database name is not set., caused by: Database name is not set.

Tested with Mendix 7.23.7 and Mendix 8.13.0.